apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: helloworld-ansible
spec:
  forProvider:
    playbookInline: |
      ---
      - hosts: localhost
        tasks:
          - name: ansibleplaybook-simple
            debug:
              msg: Hello world!
